### ISSUE TITLE
Issue with CLI - `Error: unknown protocol: 'null'` in v1.7.0, v1.7.0-1 & v1.7.0-2

### ISSUE THREAD

**Issue by jojobyte** [dashhive/crowdnode.js#48]
@coolaj86 The latest versions of `crowdnode` (v1.7.0, v1.7.0-1 & v1.7.0-2) throw this error for many of the calls that access services through `@root/request`

```sh
j@crux:~$ crowdnode status
Selected default staking key <KEY>
Fail:
Error: unknown protocol: 'null'
    at urequestHelper (~/.local/opt/node-v16.18.1/lib/node_modules/crowdnode/node_modules/@root/request/request.js:478:16)
    at urequest (~/.local/opt/node-v16.18.1/lib/node_modules/crowdnode/node_modules/@root/request/request.js:626:16)
    at ~/.local/opt/node-v16.18.1/lib/node_modules/crowdnode/node_modules/@root/request/request.js:637:17
    at new Promise (<anonymous>)
    at ~/.local/opt/node-v16.18.1/lib/node_modules/crowdnode/node_modules/@root/request/request.js:636:20
    at request (~/.local/opt/node-v16.18.1/lib/node_modules/crowdnode/node_modules/dashsight/lib/request.js:16:20)
    at Object.insight.getTxs (~/.local/opt/node-v16.18.1/lib/node_modules/crowdnode/node_modules/dashsight/dashsight.js:113:26)
    at Object.CrowdNode.status (~/.local/opt/node-v16.18.1/lib/node_modules/crowdnode/crowdnode.js:107:44)
    at getCrowdNodeStatus (~/.local/opt/node-v16.18.1/lib/node_modules/crowdnode/bin/crowdnode.js:581:32)
    at getStatus (~/.local/opt/node-v16.18.1/lib/node_modules/crowdnode/bin/crowdnode.js:1783:21)
```

While this error seems connected to this chunk of code in request.js https://github.com/therootcompany/request.js/blob/main/request.js#L467-L480

It is likely due to the `baseUrl` set to empty 👇🏼 
https://github.com/dashhive/crowdnode.js/blob/d9882fdc796fd15b490e2bbf25273d5a5761ae45/crowdnode.js#L21

Not positive that is the issue, but that's my suspicion at this point.

Rolling back to `crowdnode@v1.7.0-0` appears to get the CLI working again

```sh
npm i -g crowdnode@v1.7.0-0
```

**Comment by jojobyte** [comment]
Appears to be resolved by https://github.com/dashhive/crowdnode.js/tree/v1.8.0
